version: "3"
services:
#  hello_world:
#    image: isaac/hello_world:1.0.0
#    ports:
#    - "8080:8080"
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=eagle_eye_dev
    restart: always
  configserver:
    image: isaac/confsvr:1.0.0
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEY: "BAOCAIXUEDASHUAIGE"
    restart: always
  eurekasvr:
    image: isaac/eurekasvr:1.0.0
    ports:
    - "8761:8761"
    restart: always
  licensingservice:
    image: isaac/licensing-service:1.0.0
    ports:
    - "8082:8082"
    environment:
      ENCRYPT_KEY: "BAOCAIXUEDASHUAIGE"
      SPRING_PROFILES_ACTIVE: "lc"
      spring.cloud.config.uri: "http://configserver:8888"
      eureka.client.service-url.defaultZone: "http://eurekasvr:8761/eureka/"
    restart: always
  organizationservice:
    image: isaac/organization-service:1.0.0
    ports:
    - "8085:8085"
    environment:
      ENCRYPT_KEY: "BAOCAIXUEDASHUAIGE"
      SPRING_PROFILES_ACTIVE: "lc"
      spring.cloud.config.uri: "http://configserver:8888"
      eureka.client.service-url.defaultZone: "http://eurekasvr:8761/eureka/"
    restart: always