version: "2.2"
services:
#  hello_world:
#    image: isaac/hello_world:1.0.0
#    ports:
#    - "8080:8080"
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=eagle_eye_dev
  configserver:
    image: isaac/confsvr:1.0.0
    ports:
      - "8888:8888"
    environment:
      "ENCRYPT_KEY": "BAOCAIXUEDASHUAIGE"
  eurekasvr:
    image: isaac/eurekasvr:1.0.0
    ports:
    - "8761:8761"
  licensingservice:
    image: isaac/licensing-service:1.0.0
    ports:
    - "8082:8082"
    environment:
      "ENCRYPT_KEY": "BAOCAIXUEDASHUAIGE"
    depends_on:
      - configserver
      - database
      - eurekasvr
  organizationservice:
    image: isaac/organization-service:1.0.0
    ports:
    - "8085:8085"
    environment:
      "ENCRYPT_KEY": "BAOCAIXUEDASHUAIGE"
    depends_on:
      - configserver
      - database
      - eurekasvr