version: "2.2"
services:
#  hello_world:
#    image: isaac/hello_world:1.0.0
#    ports:
#    - "8080:8080"
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=eagle_eye_dev
  configserver:
    image: isaac/confsvr:1.0.0
    ports:
      - "8888:8888"
#  licensingservice:
#    image: isaac/licensing:1.0.0
#    ports:
#    - "8082:8082"


