version: "3"
services:
#  hello_world:
#    image: isaac/hello_world:1.0.0
#    ports:
#    - "8080:8080"
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=eagle_eye_dev
    restart: always
  configserver:
    image: isaac/confsvr:1.0.0
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEY: "BAOCAIXUEDASHUAIGE"
    restart: always
  eurekasvr:
    image: isaac/eurekasvr:1.0.0
    ports:
    - "8761:8761"
    restart: always
  licensingservice:
    image: isaac/licensing-service:1.0.0
    ports:
    - "8082:8082"
    environment:
      ENCRYPT_KEY: "BAOCAIXUEDASHUAIGE"
      SPRING_PROFILES_ACTIVE: "lc"
      spring.cloud.config.uri: "http://configserver:8888"
      eureka.client.service-url.defaultZone: "http://eurekasvr:8761/eureka/"
    restart: always
  organizationservice:
    image: isaac/organization-service:1.0.0
    ports:
    - "8085:8085"
    environment:
      ENCRYPT_KEY: "BAOCAIXUEDASHUAIGE"
      SPRING_PROFILES_ACTIVE: "lc"
      spring.cloud.config.uri: "http://configserver:8888"
      eureka.client.service-url.defaultZone: "http://eurekasvr:8761/eureka/"
    restart: always
#  orgservice-new:
#    image: isaac/orgservice-new:1.0.0
#    ports:
#    - "8087:8087"
#    environment:
#      ENCRYPT_KEY: "BAOCAIXUEDASHUAIGE"
#      SPRING_PROFILES_ACTIVE: "lc"
#      spring.cloud.config.uri: "http://configserver:8888"
#      eureka.client.service-url.defaultZone: "http://eurekasvr:8761/eureka/"
#    restart: always
#  specialroutes-service:
#    image: isaac/specialroutes-service:1.0.0
#    ports:
#    - "8910:8910"
#    environment:
#      ENCRYPT_KEY: "BAOCAIXUEDASHUAIGE"
#      SPRING_PROFILES_ACTIVE: "lc"
#      spring.cloud.config.uri: "http://configserver:8888"
#      eureka.client.service-url.defaultZone: "http://eurekasvr:8761/eureka/"
#    restart: always
  zuulserver:
    image: isaac/zuulsvr:1.0.0
    ports:
      - "5555:5555"
    environment:
      SPRING_PROFILES_ACTIVE: "lc"
      spring.cloud.config.uri: "http://configserver:8888"
      eureka.client.service-url.defaultZone: "http://eurekasvr:8761/eureka/"
    restart: always
  authenticationservice:
    image: isaac/authentication-service:1.0.0
    ports:
    - "8901:8901"
    environment:
      SPRING_PROFILES_ACTIVE: "lc"
      ENCRYPT_KEY: "BAOCAIXUEDASHUAIGE"
      spring.cloud.config.uri: "http://configserver:8888"
      eureka.client.service-url.defaultZone: "http://eurekasvr:8761/eureka/"
    restart: always
  rabbitserver:
    image: rabbitmq:management
    ports:
    - "4369:4369"
    - "5672:5672"
    - "15672:15672"
    - "25672:25672"
  redis:
    image: redis:6.0-rc3
    ports:
    - "6379:6379"
