server:
  port: 8888
spring:
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        encrypt:
#          enabled: off
#        native:
#          search-locations: classpath:/config
        git:
          uri:  https://gitee.com/har4cte/config-repo #https://github.com/baocaixue/config-repo
          searchPaths: licensingservice,organizationservice
#          username: 964c0016e7dac259c78cac12c5f822ee6c7097f3699586e7f68417abb79f9c5400831ab1129bdd7f8169cb74aedabe8e
#          password: cfa99af3c3f25860797e8ffe2bdf32e879fcb887b079af10bdf6aa0dfcb09d13
#          timeout: 1024102410
      label: master
      discovery:
        enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekasvr:8761/eureka/