POST http://localhost:8085/v1/organizations
Accept: */*
Cache-Control: no-cache
Authorization: Bearer 7b87e392-97a3-475f-9924-6917070871ff
Content-Type: application/json

{      "name": "test",   "contactName": "test",   "contactEmail": "test@gmail.com",   "contactPhone": "11111" }

###
