POST http://localhost:8086/v1/organizations
Accept: */*
Cache-Control: no-cache
Authorization: Bearer 947e0a9c-0202-43fe-984a-21d9e4958bc1
Content-Type: application/json

{      "name": "test",   "contactName": "test",   "contactEmail": "test@gmail.com",   "contactPhone": "11111" }

###
