# Refresh Routes
POST http://localhost:5555/actuator/refresh
Accept: */*
Cache-Control: no-cache
###

# Get all Routes
GET http://localhost:5555/actuator/routes
Accept: */*
Cache-Control: no-cache
###

# License
GET http://localhost:5555/api/licensing/v1/organizations/e254f8c-c442-4ebe-a82a-e2fc1d1ff78a/licenses/f3831f8c-c338-4ebe-a82a-e2fc1d1ff78a
Accept: */*
Cache-Control: no-cache
Authorization: Bearer 7b87e392-97a3-475f-9924-6917070871ff
###
